name: CMake Multi-Platform Build

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        cmake_version: [3.16.3, 3.18.4, 3.21.1]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up CMake
      uses: jwlawson/actions-setup-cmake@v1
      with:
        cmake-version: ${{ matrix.cmake_version }}

    - name: Configure CMake
      run: cmake -S . -B build

    - name: Build
      run: cmake --build build --config Release

    - name: Run Tests
      run: ctest --test-dir build --output-on-failure
      if: success()

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: fftp_binaries_${{ matrix.os }}
        path: build/
